name: AutoBuild

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*.*'

jobs:

  build-and-push:
    name: Build, Test and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_OUTPUT"
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUBUSER }}
          password: ${{ secrets.DOCKERHUBPAT }}

      - name: Build and push production image
        uses: docker/build-push-action@v6
        with:
          context: ./tools/
          file: ./tools/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUBUSER }}/${{ secrets.DOCKERHUBPROJECTNAME }}:${{ steps.meta.outputs.SHORT_SHA }}
            ${{ secrets.DOCKERHUBUSER }}/${{ secrets.DOCKERHUBPROJECTNAME }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Extract built image artifacts
        uses: shrink/actions-docker-extract@v3
        id: extract
        with:
          image: ${{ secrets.DOCKERHUBUSER }}/${{ secrets.DOCKERHUBPROJECTNAME }}:latest
          path: /opt/drawthenet.io/.
          destination: dist

      - name: Zip dist folder
        run: zip -r drawthenet.io-AutoBuild-${{ steps.date.outputs.date }}-dist-${{ steps.meta.outputs.SHORT_SHA }}.zip dist/*

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: drawthenet.io-AutoBuild-${{ steps.date.outputs.date }}-dist-${{ steps.meta.outputs.SHORT_SHA }}
          path: dist/*


      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: drawthenet.io-AutoBuild-${{ steps.date.outputs.date }}-dist-${{ steps.meta.outputs.SHORT_SHA }}.zip
          generate_release_notes: true
          draft: false
          prerelease: false
          name: AutoBuild-${{ steps.date.outputs.date }}-dist-${{ steps.meta.outputs.SHORT_SHA }}
          tag_name: AutoBuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}